name = "cloth-frontend"
main = "src/index.ts"
compatibility_date = "2024-08-01"
account_id = "89e710f9bb3d66a7882e44e5158bda84"

[build]
command = "npm ci && npm run build && mkdir -p ./public && cp -r build/client/* ./public/"

[assets]
directory = "./public"
binding = "ASSETS"

[env.development]
name = "cloth-frontend-dev"

[env.production]  
name = "cloth-frontend"