name = "cloth-api"
main = "build/worker/shim.mjs"
compatibility_date = "2024-08-01"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[kv_namespaces]]
binding = "FLAGS"
preview_id = "a08ec0798553499188c009d1fac459a8"
id = "ed67b444ef2a402bad2242198a99199d"

[env.development]
name = "cloth-api-dev"

[[env.development.kv_namespaces]]
binding = "FLAGS"
preview_id = "a08ec0798553499188c009d1fac459a8"

[env.production]
name = "cloth-api-prod"

[[env.production.kv_namespaces]]
binding = "FLAGS"
id = "ed67b444ef2a402bad2242198a99199d"